spring:
  application:
    name: UserService
  profiles:
    active: dev
  security:
    user:
      name: user  # Replace with your desired username
      password: user  # Replace with your desired password
      roles: USER

  data:
    mongodb:
      host: localhost
      port: 27017
      database: JobBuddy

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /openapi.json

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG